- hosts: all
  become: true
  tasks:
    - name: create pod
      command: kubectl apply -f /home/ec2-user/deploy01.yml
    - name: create service to access website
      command: kubectl apply -f /home/ec2-user/service.yml
